### PR TITLE
gewman twanswation nya~

### PR DESCRIPTION
**Pull request by Fateussy**
Nyow **UPDATE** the x3 [modewation fowdew](https://github.com/FrequencyX4/FateTranslations/commits?author=FrequencyX4)!! [_*cries in a moe way_*](https://store.steampowered.com/app/333600/NEKOPARA_Vol_1)

### CODE REVIEW

**Comment by netkek0** [comment]
what in the UwU catgirl....

**Comment by Luckolite** [comment]
someone verify the changes aren't cursed

**Comment by netkek0** [comment]
all are right, none are cursed

**Comment by Fateussy** [comment]
the twanswation awe safe ;;w;; hihihihihi *twerks* @FrequencyX4

**Comment by netkek0** [comment]
damn, luck be getting all the twerks on him :(

**Pull request merged**
